version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=KpasDEV
      - MYSQL_ROOT_PASSWORD=KpasDEV
    ports:
      - '3310:3310'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  kpas:
    container_name: kpas
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      APP_DEBUG: "true"
      APP_ENV: "local"
      APP_NAME: "KPAS DEV"
      APP_URL: "https://audun-kpas.eu.ngrok.io"
      LOG_CHANNEL: "stack"
      DEBUGBAR_ENABLED: "true"
      CANVAS_HOST: "https://bibsys.test.instructure.com"
      DB_CONNECTION: mysql
      DB_HOST: docker.for.mac.localhost
      DB_PORT: 3306
      DB_USERNAME: kpas2
      DB_PASSWORD: kpas2
      DB_DATABASE: kpas2
      KPAS_API_ACCESS_TOKEN: "1234567890abcdefghkwej0128"
    links:
      - db
    volumes:
      - ./:/src
volumes:
  db:
    driver: local

