version: '3.8'
services:
  kpas_db:
    image: mysql:8.0
    container_name: kpas_db
    environment:
      MYSQL_DATABASE: db_kpas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: usr_app_kpas
      MYSQL_PASSWORD: Password@123
    volumes:
      - kpas_db_data:/var/lib/mysql
    ports:
      - "3315:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kpas_network

  kpas_app:
    build: .docker
    container_name: kpas_app
    depends_on:
      kpas_db:
        condition: service_healthy
    environment:
      APP_URL: "" # ngrok http http://localhost:8080 --subdomain udir-kpas-api-<ReplaceWithYourName>
      CANVAS_ACCESS_KEY: "" # Generate a new access key here: https://bibsys.test.instructure.com/profile/settings
    volumes:
      - ./:/var/www/html
      - .docker/nginx.conf:/etc/nginx/nginx.conf
      - .docker/fpm-pool.conf:/usr/local/etc/php/php-fpm.d/www.conf
      - .docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - .docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - .docker/startup.sh:/var/www/html/startup.sh
      - kpas_nvm_data:/usr/local/nvm
      - kpas_npm_data:/var/www/.npm
      - kpas_composer_data:/var/www/.composer
    ports:
      - "8080:8080"
    networks:
      - kpas_network

networks:
  kpas_network:
    driver: bridge

volumes:
  kpas_db_data:
  kpas_nvm_data:
  kpas_npm_data:
  kpas_composer_data:
