# Go Setup Action
# Reusable action for setting up Go environment with caching
# Copy to other projects: .github/actions/_go-setup/

name: 'Go Setup'
description: 'Set up Go environment with module caching'

inputs:
  go-version:
    description: 'Go version to install'
    required: false
    default: '1.24'
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'
  skip-download:
    description: 'Skip go mod download (for vendored dependencies)'
    required: false
    default: 'false'
  skip-verify:
    description: 'Skip go mod verify (faster but less safe)'
    required: false
    default: 'false'

outputs:
  go-version:
    description: 'Installed Go version'
    value: ${{ steps.setup.outputs.go-version }}
  cache-hit:
    description: 'Whether cache was hit'
    value: ${{ steps.setup.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Check for Go module
      id: check-mod
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f "go.mod" ]; then
          echo "has_go_mod=true" >> $GITHUB_OUTPUT
          echo "Go module found"
        else
          echo "has_go_mod=false" >> $GITHUB_OUTPUT
          echo "No go.mod found - skipping Go module setup"
        fi

    - name: Set up Go ${{ inputs.go-version }}
      id: setup
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: ${{ steps.check-mod.outputs.has_go_mod == 'true' }}
        cache-dependency-path: ${{ inputs.working-directory }}/go.sum

    - name: Verify Go installation
      shell: bash
      run: |
        if ! command -v go &> /dev/null; then
          echo "::error::Go installation failed - command not found"
          exit 1
        fi
        echo "go: $(go version)"

    - name: Download dependencies
      if: inputs.skip-download != 'true' && steps.check-mod.outputs.has_go_mod == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: go mod download

    - name: Verify dependencies
      if: inputs.skip-verify != 'true' && steps.check-mod.outputs.has_go_mod == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: go mod verify
