on:
    workflow_call:
        inputs:
            azure_client_id:
                type: string
                description: 'Azure client ID'
                required: true
            azure_tenant_id:
                type: string
                description: 'Azure tenant ID'
                required: true
            azure_subscription_id:
                type: string
                description: 'Azure subscription ID'
                required: true
            azure_app_service_name:
                type: string
                description: 'Azure App Service name'
                required: true
            azure_resource_group:
                type: string
                description: 'Azure resource group'
                required: true
            docker_registry:
                type: string
                description: 'Docker registry URL'
                required: true
            docker_username:
                type: string
                description: 'Docker registry username'
                required: true
            docker_image:
                type: string
                description: 'Docker image name'
                required: true
        secrets:
            docker_password:
                description: 'Docker registry password'
                required: false

jobs:
    deploy-app:
        name: Deploy - App
        runs-on: ubuntu-latest
        if: contains('refs/heads/stage refs/heads/main', github.ref)
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ inputs.azure_client_id }}
                  tenant-id: ${{ inputs.azure_tenant_id }}
                  subscription-id: ${{ inputs.azure_subscription_id }}

            - name: Deploy Docker Image to Azure App Service
              uses: azure/cli@v2
              with:
                  inlineScript: |
                      az webapp config container set \
                        --name ${{ inputs.azure_app_service_name }} \
                        --resource-group ${{ inputs.azure_resource_group }} \
                        --container-image-name ${{ inputs.docker_registry }}/${{ inputs.docker_image }}:CI-${{ github.sha }} \
                        --container-registry-url https://${{ inputs.docker_registry }} \
                        --container-registry-user ${{ inputs.docker_username }} \
                        --container-registry-password ${{ secrets.docker_password }}
            
            - name: Restart Azure App Service
              uses: azure/cli@v2
              with:
                  inlineScript: |
                      sleep 5
                      az webapp restart \
                        --name ${{ inputs.azure_app_service_name }} \
                        --resource-group ${{ inputs.azure_resource_group }}
